#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Yashwanth Yadavalli <yashwanth.yadavalli@protonmail.com>

# XDG Base directory specification
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

# Coursier cache
export COURSIER_CACHE="${XDG_CACHE_HOME}/coursier/cache/v1"

# CUDA
export CUDA_CACHE_PATH="${XDG_CACHE_HOME}/nv"

# Docker
export DOCKER_CONFIG="${XDG_CONFIG_HOME}/docker"

# Doom Emacs
export DOOMDIR="${XDG_CONFIG_HOME}/doom"

# Gdrive
export GDRIVE_CONFIG_DIR="${XDG_DATA_HOME}/gdrive"

# GnuPG
export GNUPGHOME="${XDG_CONFIG_HOME}/gnupg"
export GPG_TTY=$(tty)

# Gradle
export GRADLE_HOME="${XDG_CONFIG_HOME}/gradle"
export GRADLE_USER_HOME="${XDG_CACHE_HOME}/gradle"

# Haskell - cabal-install configuration
export CABAL_CONFIG="${XDG_CONFIG_HOME}/cabal/config"

# Haskell - stack configuration
export STACK_ROOT="$HOME/Applications/stack"

# INPUTRC
export INPUTRC="${XDG_CONFIG_HOME}/inputrc"

# Jupyter notebooks
export JUPYTER_CONFIG_DIR="${XDG_CONFIG_HOME}/jupyter"
export IPYTHONDIR="${XDG_CONFIG_HOME}/ipython"

# Lein
export LEIN_HOME="${XDG_CONFIG_HOME}/lein"

# less
export LESSKEY="$XDG_CONFIG_HOME"/less/lesskey
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history

# Node.js, NPM and nodenv
export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"

# Python version Manager
export PYLINTHOME="$XDG_CACHE_HOME/pylint"

# Postgres
export PSQLRC="$XDG_CONFIG_HOME/pg/psqlrc"
export PSQL_HISTORY="$XDG_CACHE_HOME/pg/psql_history"
export PGPASSFILE="$XDG_CONFIG_HOME/pg/pgpass"
export PGSERVICEFILE="$XDG_CONFIG_HOME/pg/pg_service.conf"

# Terminfo
export TERMINFO="${XDG_DATA_HOME}/terminfo"

# Vagrant
export VAGRANT_HOME="${XDG_DATA_HOME}/vagrant"
export VAGRANT_ALIAS_FILE="${XDG_DATA_HOME}/vagrant/aliases"

# Xauthority cookies
export XAUTHORITY="${XDG_CACHE_HOME}/Xauthority"

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
