#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Yashwanth Yadavalli <yashwanth.yadavalli@protonmail.com>

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Profile emacs startup time
alias ep="time emacs --batch -l ~/.config/emacs/init.el --eval '(message \"Hello\")'"

# nvim as default for vi
alias vi="nvim"
alias vim="nvim"

# Ammonite REPL
alias amm="amm -h ${XDG_CONFIG_HOME}/ammonite"

# Bat - A cat(1) clone with wings
alias cat="bat"

# ctags
alias ctags="ctags --options=${XDG_CONFIG_HOME}/ctags.conf"

# Hoogle with custom database location
alias hoogle="hoogle --database ${XDG_DATA_HOME}/hoogle/default.hoo"

# isync (mbsync)
alias mbsync="mbsync -c ${XDG_CONFIG_HOME}/isync/mbsyncrc"

# Maven
alias mvn="mvn -gs ${XDG_CONFIG_HOME}/maven/settings.xml"

# Loop setup for iso files
alias loopiso="udisksctl loop-setup -r -f"

# Use QtWebEngine for qutebrowser
alias qutebrowser="qutebrowser --backend webengine"

# Replace tree (& variants) with exa aliases
alias tree="exa --tree"
alias stree="tree -I target"

# tmux with config file
alias tmux="tmux -f ${XDG_CONFIG_HOME}/tmux.conf"

# wget
alias wget="wget --hsts-file=${XDG_CACHE_HOME}/wget-hsts"

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh

# Brazil
alias bb=brazil-build

alias bba='bb apollo-pkg'
alias bbr='bb release'
alias bre='brazil-runtime-exec'
alias brc='brazil-recursive-cmd'
alias bws='brazil ws'
alias bwsuse='bws use --gitMode -p'
alias bwscreate='bws create -n'
alias bbR='brc brazil-build'
alias bball='brc --allPackages'
alias bbb='bball brazil-build'
alias bbra='bbr apollo-pkg'

alias grm='for file in .git/refs/wip/wtree/refs/heads/*; rm $file'
